export const container = createElement("div", document.body, "container");
export const textarea = createElement("textarea", container, "textarea");
textarea.setAttribute("cols", "75");
textarea.setAttribute("rows", "10");

export const keyboard = createElement("div", container, "keyboard");
export const  row1 = createElement("div", keyboard, "row");
export const  row2 = createElement("div", keyboard, "row");
export const  row3 = createElement("div", keyboard, "row");
export const  row4 = createElement("div", keyboard, "row");
export const  row5 = createElement("div", keyboard, "row");

export const  button1 = createButton("button", row1, "basic", "Backquote", "ё");
export const  button2 = createButton("button", row1, "basic", "Digit1", "1");
export const  button3 = createButton("button", row1, "basic", "Digit2", "2");
export const  button4 = createButton("button", row1, "basic", "Digit3", "3");
export const  button5 = createButton("button", row1, "basic", "Digit4", "4");
export const  button6 = createButton("button", row1, "basic", "Digit5", "5");
export const  button7 = createButton("button", row1, "basic", "Digit6", "6");
export const  button8 = createButton("button", row1, "basic", "Digit7", "7");
export const  button9 = createButton("button", row1, "basic", "Digit8", "8");
export const  button10 = createButton("button", row1, "basic", "Digit9", "9");
export const  button11 = createButton("button", row1, "basic", "Digit0", "0");
export const  button12 = createButton("button", row1, "basic", "Minus", "-");
export const  button13 = createButton("button", row1, "basic", "Equal", "=");
export const  button14 = createButton("button", row1, "backspace", "Backspace", "Backspace");
export const  button15 = createButton("button", row2, "tab", "Tab", "Tab");
export const  button16 = createButton("button", row2, "basic", "KeyQ", "й");
export const  button17 = createButton("button", row2, "basic", "KeyW", "ц");
export const  button18 = createButton("button", row2, "basic", "KeyE", "у");
export const  button19 = createButton("button", row2, "basic", "KeyR", "к");
export const  button20 = createButton("button", row2, "basic", "KeyT", "е");
export const  button21 = createButton("button", row2, "basic", "KeyY", "н");
export const  button22 = createButton("button", row2, "basic", "KeyU", "г");
export const  button23 = createButton("button", row2, "basic", "KeyI", "ш");
export const  button24 = createButton("button", row2, "basic", "KeyO", "щ");
export const  button25 = createButton("button", row2, "basic", "KeyP", "з");
export const  button26 = createButton("button", row2, "basic", "BracketLeft", "х");
export const  button27 = createButton("button", row2, "basic", "BracketRight", "ъ");
export const  button28 = createButton("button", row2, "basic", "Backslash", "\\");
export const  button29 = createButton("button", row2, "del", "Delete", "Del");
export const  button30 = createButton("button", row3, "caps-lock", "CapsLock", "CapsLock");
export const  button31 = createButton("button", row3, "basic", "KeyA", "ф");
export const  button32 = createButton("button", row3, "basic", "KeyS", "ы");
export const  button33 = createButton("button", row3, "basic", "KeyD", "в");
export const  button34 = createButton("button", row3, "basic", "KeyF", "а");
export const  button35 = createButton("button", row3, "basic", "KeyG", "п");
export const  button36 = createButton("button", row3, "basic", "KeyH", "р");
export const  button37 = createButton("button", row3, "basic", "KeyJ", "о");
export const  button38 = createButton("button", row3, "basic", "KeyK", "л");
export const  button39 = createButton("button", row3, "basic", "KeyL", "д");
export const  button40 = createButton("button", row3, "basic", "Semicolon", "ж");
export const  button41 = createButton("button", row3, "basic", "Quote", "э");
export const  button42 = createButton("button", row3, "enter", "Enter", "Enter");
export const  button43 = createButton("button", row4, "shift", "ShiftLeft", "Shift");
export const  button44 = createButton("button", row4, "basic", "KeyZ", "я");
export const  button45 = createButton("button", row4, "basic", "KeyX", "ч");
export const  button46 = createButton("button", row4, "basic", "KeyC", "с");
export const  button47 = createButton("button", row4, "basic", "KeyV", "м");
export const  button48 = createButton("button", row4, "basic", "KeyB", "и");
export const  button49 = createButton("button", row4, "basic", "KeyN", "т");
export const  button50 = createButton("button", row4, "basic", "KeyM", "ь");
export const  button51 = createButton("button", row4, "basic", "Comma", "б");
export const  button52 = createButton("button", row4, "basic", "Period", "ю");
export const  button53 = createButton("button", row4, "basic", "Slash", ".");
export const  button54 = createButton("button", row4, "basic", "ArrowUp", "&#9650");
export const  button55 = createButton("button", row4, "shift", "ShiftRight", "Shift");
export const  button56 = createButton("button", row5, "basic", "ControlLeft", "Ctrl");
export const  button57 = createButton("button", row5, "basic", "MetaLeft", "Win");
export const  button58 = createButton("button", row5, "basic", "AltLeft", "Alt");
export const  button59 = createButton("button", row5, "space", "Space", "");
export const  button60 = createButton("button", row5, "basic", "AltRight", "Alt");
export const  button61 = createButton("button", row5, "basic", "ArrowLeft", "◄");
export const  button62 = createButton("button", row5, "basic", "ArrowDown", "▼");
export const  button63 = createButton("button", row5, "basic", "ArrowRight", "►");
export const  button64 = createButton("button", row5, "basic", "ControlRight", "Ctrl");
button43.classList.add("shift-left");
button54.classList.add("basic-dark");
button55.classList.add("shift-right");
[button56, button57, button58, button60, button61, button62, button63, button64].forEach((item) => item.classList.add("basic-dark"));


export const buttons = document.querySelectorAll("button");
